#!/usr/bin/env bash

if ! command -v brew &>/dev/null; then
  NONINTERACTIVE=1  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! brew ls --versions pyenv > /dev/null; then
  
  brew install pyenv

  echo export PYENV_ROOT="$HOME/.pyenv" >> ~/.bashrc
  echo command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH" >> ~/.bashrc
  echo eval "$(pyenv init -)" >> ~/.bashrc

  source ~/.bashrc

  pyenv install 3.9.0
fi

pyenv global 3.9.0

if ! [ -d "venv" ]; then
  python -m venv venv
fi

source venv/bin/activate

pip install --upgrade pip

pip install -r requirements.txt
